server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
bank:
  notes: 1,2,5,10,20,50,100
  coins: 1,5,10,25,33,34